#!/bin/bash

git rm -r --cached .config/albert
git rm -r --cached .config/autostart
git rm -r --cached .config/bauh
git rm -r --cached .config/clipit
git rm -r --cached .config/cmus
git rm -r --cached .config/Code
git rm -r --cached .config/compton.conf
git rm -r --cached .config/configstore
git rm -r --cached .config/dconf
git rm -r --cached .config/discord
git rm -r --cached .config/dmenu-recent
git rm -r --cached .config/epdfview
git rm -r --cached .config/falkon
git rm -r --cached .config/gconf
git rm -r --cached .config/google-chrome
git rm -r --cached .config/gtk-2.0
git rm -r --cached .config/gtk-3.0
git rm -r --cached .config/hexchat
git rm -r --cached .config/htop
git rm -r --cached .config/JetBrains
git rm -r --cached .config/Jitsi Meet
git rm -r --cached .config/Kvantum
git rm -r --cached .config/libfm
git rm -r --cached .config/manjaro
git rm -r --cached .config/manjaro-hello.json
git rm -r --cached .config/menus
git rm -r --cached .config/mimeapps.list
git rm -r --cached .config/mono.addins
git rm -r --cached .config/morc_menu
git rm -r --cached .config/Mousepad
git rm -r --cached .config/neofetch
git rm -r --cached .config/nitrogen
git rm -r --cached .config/Notion
git rm -r --cached .config/obs-studio
git rm -r --cached .config/pamac
git rm -r --cached .config/pavucontrol.ini
git rm -r --cached .config/pcmanfm
git rm -r --cached .config/Pinta
git rm -r --cached .config/pulse
git rm -r --cached .config/qt5ct
git rm -r --cached .config/QtProject.conf
git rm -r --cached .config/ranger
git rm -r --cached .config/spotify
git rm -r --cached .config/user-dirs.dirs
git rm -r --cached .config/user-dirs.locale
git rm -r --cached .config/viewnior
git rm -r --cached .config/VirtualBox
git rm -r --cached .config/vlc
git rm -r --cached .config/volumeicon
git rm -r --cached .config/xarchiver
git rm -r --cached .config/xbuild
git rm -r --cached .config/xfce4
git rm -r --cached .config/yay