'use strict';window.requestFileSystem||(window.requestFileSystem=window.webkitRequestFileSystem);window.BlobBuilder||(window.BlobBuilder=window.WebKitBlobBuilder);
Registry.require("promise layout xmlhttprequest convert crcrc curtain layout/default/tabview layout/default/htmlutil helper i18n parser statistics layout/default/layout_helper".split(" "),()=>{const z=rea.FEATURES,D=Registry.get("promise"),m=Registry.get("crcrc").cr,c=Registry.get("crcrc").crc,g=Registry.get("i18n"),E=Registry.get("curtain"),w=Registry.get("helper"),L=Registry.get("layout/default/tabview"),u=Registry.get("layout/default/htmlutil"),X=Registry.get("statistics"),H=Registry.get("layout"),
M=Registry.get("layout/default/layout_helper"),A=M.images;H.render(()=>{let k=null,t={},N="???",F=null,O="0.0.0";const q=(b,a,f)=>{f=f||{};const e=D();try{const c={aid:b,method:a};f.data&&w.each(f.data,(a,b)=>{c[b]=f.data[b]});sendMessage({method:"askCom",data:c},a=>{f.bg||E.hide();t=a.options||t;a.error?(a.please_close&&window.setTimeout(window.close,100),e.reject(a)):e.resolve(a)});f.bg||E.wait(g.getMessage("Please_wait___"))}catch(d){console.warn("sS: "+d.message),e.reject()}return e.promise()},
H=()=>q(k.aid,"ping",{bg:!0}),Y=(b,a,c)=>{try{sendMessage(w.assign({method:"buttonPress",name:b},a),a=>{c&&c(a)})}catch(e){console.log("button: "+e.message)}},B=()=>{var b=c("div","content_wrapper","ask","main");$(document.body).append(b).addClass("main");var a=c("div","head_container","ask","head_container"),f=c("div","tv_container_fit","ask","tv_container");const e=m("a","head_link","ask","head_link");e.href="https://www.tampermonkey.net";e.target="_blank";const d=c("div","float","ask","head1"),
h=c("img","banner","ask");h.src=A.brand("tampermonkey");const g=c("div","float head","ask","head2"),l=c("div","header_title","heading"),p=c("div","version","version","version");p.textContent=" by Jan Biniok";const G=m("div","search","box","");l.innerHTML="Tampermonkey<sup>&reg;</sup>";d.appendChild(h);g.appendChild(l);g.appendChild(p);e.appendChild(d);e.appendChild(g);a.appendChild(e);a.appendChild(G);b.appendChild(a);b.appendChild(f);b=L.create("_main",f);a=m("div","main","main","tab_content_h");
a.textContent=N;f=m("div","main","main","tab_content");b.appendTab(w.createUniqueId("main","main"),a,f).select();b=f;E.hide();return b},Z=b=>{const a=b.script,f=b.oldscript,e=c("div","viewer_bottom_tab","bottom","");b={tv:"tv tv_alt",tv_table:"tv_table tv_table_alt",tr_tabs:"tr_tabs tr_tabs_alt",tr_content:"tr_content tr_content_alt",td_content:"td_content td_content_alt",td_tabs:"td_tabs td_tabs_alt",tv_tabs_align:"tv_tabs_align tv_tabs_align_alt",tv_tabs_fill:"tv_tabs_fill tv_tabs_fill_alt",tv_tabs_table:"tv_tabs_table tv_tabs_table_alt",
tv_contents:"tv_contents tv_contents_alt",tv_tab_selected:"tv_tab tv_selected tv_tab_alt tv_selected_alt",tv_tab_close:"",tv_tab:"tv_tab tv_tab_alt",tv_content:"tv_content tv_content_alt"};if(t.editor_enabled){const d=L.create("_source"+a.uuid,e,b);let n;const l=(a,b)=>{const f=c("div","tv_content tv_content_alt",a.uuid,b+"container_o");var e=c("table","editor_container_o editor_400p_container_o p100100 noborder",a.uuid,b+"container_o");const d=c("tr","editor_container p100100",a.uuid,b+"container");
f.appendChild(e);e.appendChild(d);e=c("td","editor_outer editor_400p_outer",a.uuid,b+"edit");a=c("div","editor_100 editor_border",a.uuid,b+"edit");d.appendChild(e);e.appendChild(a);return{c:f,e:a}};let p=()=>{const a=D();rea.page.addStyle("vendor/cm/mode/diff/diff.css");Registry.vendor(["vendor/jsdiff/diff","vendor/cm/mode/diff/diff"],()=>{p=D.Pledge;a.resolve()});return a.promise()};(()=>f&&f.textContent!=a.textContent?p().then(()=>{const b=m("div",a.uuid,"diff_h");b.textContent=g.getMessage("Changes");
const c=l(a,"diff");e.diff=new MirrorFrame(c.e,{theme:"diff",fontSize:t.editor_fontSize,value:g.getMessage("Please_wait___"),noButtons:!0,mode:"diff",readOnly:!0});n=d.appendTab("diff",b,c.c,()=>{window.setTimeout(()=>{e.diff.refresh();e.diff.mirror.focus()},1)});window.setTimeout(()=>{let b;try{b=window.JsDiff.createTwoFilesPatch(g.getMessage("Current_Version"),g.getMessage("New_Version"),f.textContent,a.textContent,void 0,void 0,{timeout:4E3})}catch(v){console.warn(v)}b||(b=g.getMessage("The_diff_for_this_script_is_too_large_to_render"));
e.diff.mirror.setValue(b)},500)}):D.Pledge())().then(()=>{var b=m("div",a.uuid,"source_h");b.textContent=g.getMessage("Source_Code");const c=l(a,"source");e.editor=new MirrorFrame(c.e,{theme:t.editor_theme,fontSize:t.editor_fontSize,value:a.textContent,noButtons:!0,matchBrackets:!0,readOnly:!0});b=d.appendTab("source",b,c.c,()=>{window.setTimeout(()=>{e.editor.refresh();e.editor.mirror.focus()},1)});n=n||b}).then(()=>{n.select()})}else{var d=c("div","editor_400p_outer","editor",a.name);b=c("div",
"editor_400p editor_border","editor",a.name);e.appendChild(d);d.appendChild(b);d=c("textarea","editorta","editor",a.name);d.setAttribute("wrap","off");b.appendChild(d);d.value=a.textContent}return e},aa=(()=>{const b={};window.addEventListener("keydown",a=>{let c=!1;if("keydown"==a.type&&(b[a.keyCode]&&(c=b[a.keyCode](a)),c))return a.stopPropagation(),a.preventDefault(),!1},!0);return{registerListener:function(a,c){b[a]=c}}})(),x=(b,a,c)=>{w.select(c,a=>a.label).forEach(c=>{const f=c.icon?u.createImageTextButton(c.id,
c.id,c.label,c.icon,c.fn):u.createButton(c.label,c.id,c.label,c.fn),e=$(f);e.addClass(a);c.id&&e.attr("data-btn-id",c.id);b.appendChild(f);c.focus&&window.setTimeout(()=>{e.focus()},300);c.keyDown&&aa.registerListener(c.keyDown.keyCode?c.keyDown.keyCode:c.keyDown,c.keyDown.cb?c.keyDown.cb:c.fn)})},ca=b=>{const a=b.script,f=c("div","viewer_last","install"),e=c("div","viewer_content","install_content"),d=c("div","ask_action_buttons","install_buttons"),h=[];h.push({label:b.messages.action,fn:function(){q(k.aid,
"install")},focus:!0});z.RUNTIME.CHROME&&21>z.RUNTIME.BROWSER_VERSION&&h.push({label:b.messages.flags.install?g.getMessage("Process_with_Chrome"):null,fn:function(){ba(a.fileURL);$(f).hide()}});h.push({label:g.getMessage("Cancel"),fn:y,keyDown:27});x(d,"install",h);e.appendChild(d);f.appendChild(e);return f},da=b=>{const a=c("div","viewer_last","import");var f=c("div","viewer_content","import_content");const e=c("div","ask_action_buttons import_buttons","import_buttons");x(e,"import",[{label:g.getMessage("Import"),
fn:function(){const a=Object.keys(b.scripts).filter(a=>!!$("input[type=checkbox][data-import-id="+a+"]:checked").val()),c=b.global_settings&&!!$("input[type=checkbox][data-import-id=global_settings]:checked").val();q(k.aid,"import",{data:{import_ids:a,global_settings:c}})},focus:!0},{label:g.getMessage("Cancel"),fn:y,keyDown:27}]);f.appendChild(e);a.appendChild(f);f=c("div","section","btn");f.appendChild(a);return f},ea=b=>{b=c("div","viewer_last","ok");const a=c("div","viewer_content","ok_content"),
f=c("div","ask_action_buttons","ok_buttons");x(f,"import",[{label:g.getMessage("Ok"),fn:y,focus:!0}]);a.appendChild(f);b.appendChild(a);return b},fa=(b,a)=>{const f=c("div","viewer_last","ok");var e=c("div","viewer_content","ok_content"),d=c("div","ask_action_buttons","ok_buttons");x(d,"permission",[{label:g.getMessage("Ok"),fn:()=>{const b={permissions:a.permissions,origins:a.origins};rea.permissions.request(b,a=>{let c;rea.runtime.lastError&&(c=rea.runtime.lastError.message,console.warn("notify: error on getting permission",
b,"reason:",c));q(k.aid,"permission",{data:{granted:a,permissions:b.permissions,origins:b.origins,error:c}})})},focus:!0},{label:g.getMessage("Cancel"),fn:y,keyDown:27}]);e.appendChild(d);f.appendChild(e);e=c("div","viewer_upper","permission");d=c("div","viewer_info viewer_info_wide","general","permission");const h=c("div","viewer_content","general_content","permission"),n=m("h3","install","heading","permission"),l=m("span","install","heading_span","permission"),p=c("span","message","heading","permission");
document.title=l.textContent=a.title;p.innerHTML=u.safeTagsReplace(a.message).replace(/\n/g,"<br>");n.appendChild(l);h.appendChild(p);d.appendChild(n);d.appendChild(h);e.appendChild(d);d=c("div","section","perm_src","permission");d.appendChild(e);d.appendChild(f);b.appendChild(d)},ha=(b,a)=>{const f=Date.now();let e,d;a.timeout&&(e=window.setTimeout(()=>{y();h()},a.timeout));const h=()=>{let a;d&&window.clearInterval(d);e&&window.clearTimeout(e);d=e=null;(a=$("input[data-btn-id]")[0])&&a.parentNode.removeChild(a)},
n=c("div","viewer_last","ok");var l=c("div","viewer_content","ok_content");const p=c("div","ask_action_buttons","ok_buttons"),G=c("div","ask_action_buttons","ok_buttons"),r=c("div","ask_action_buttons","ok_buttons");x(p,"connect",[{label:g.getMessage("Allow_once"),icon:"button_ok",fn:function(){return q(k.aid,"connect",{data:{ok:!0,allow:!0,once:!0}})},focus:!0},{label:g.getMessage("Temporarily_allow"),icon:"clock",fn:function(){return q(k.aid,"connect",{data:{ok:!0,allow:!0,temporary:!0}})}},{label:a.hostname!=
a.domain?g.getMessage("Always_allow"):g.getMessage("Always_allow_domain"),icon:"yes_domain",fn:function(){return q(k.aid,"connect",{data:{ok:!0,allow:!0}})}},(()=>a.domain&&a.hostname!=a.domain?{label:g.getMessage("Always_allow_domain"),icon:"yes_domain",fn:function(){return q(k.aid,"connect",{data:{ok:!0,allow:!0,whole_domain:!0}})}}:null)(),(()=>a.all_domains?{label:g.getMessage("Always_allow_all_domains"),icon:"critical",fn:function(){h();if(window.confirm(g.getMessage("This_gives_this_script_the_permission_to_retrieve_and_send_data_from_and_to_every_webpage__This_is_potentially_unsafe__Are_you_sure_you_want_to_continue_")))return q(k.aid,
"connect",{data:{ok:!0,allow:!0,all_domains:!0}})}}:null)()].filter(a=>a));x(G,"connect",[{label:g.getMessage("Forbid_once"),icon:"cancel",fn:function(){return q(k.aid,"connect",{data:{ok:!0,deny:!0,once:!0}})},keyDown:27},{label:a.hostname!=a.domain?g.getMessage("Always_forbid"):g.getMessage("Always_forbid_domain"),icon:"no_domain",fn:function(){return q(k.aid,"connect",{data:{ok:!0,deny:!0}})}},(()=>a.domain&&a.hostname!=a.domain?{label:g.getMessage("Always_forbid_domain"),icon:"no",fn:function(){return q(k.aid,
"connect",{data:{ok:!0,deny:!0,whole_domain:!0}})}}:null)(),{label:g.getMessage("Dont_ask_again"),icon:"no",fn:function(){return q(k.aid,"connect",{data:{ok:!0,deny:!0,all_domains:!0}})}}].filter(a=>a));x(r,"connect_misc",[(()=>a.tabid?{label:g.getMessage("Focus_tab"),icon:"windowlist",fn:function(){Y("focus_tab",{tabid:a.tabid})}}:null)(),(()=>{if(a.timeout)return d=window.setInterval(()=>{let b;(b=$("input[data-btn-id]")[0])&&$(b).attr("value",g.getMessage("Skip_timeout__0seconds0_seconds_",Math.round((a.timeout+
f-Date.now())/1E3)))},1E3),{label:g.getMessage("Skip_timeout__0seconds0_seconds_",Math.round(a.timeout/1E3)),id:"skip_timeout_button",fn:h}})()].filter(a=>a));const t=c("div","viewer_upper","connect"),v=c("div","viewer_info viewer_info_wide","general","connect"),P=c("div","viewer_content","general_content","connect"),Q=m("h3","install","heading","connect"),I=m("span","install","heading_span","connect"),R=c("span","message","heading","connect");if(a.script.icon){var C=m("img","version","heading","connect");
C.src=a.script.icon;I.appendChild(C)}document.title=I.textContent=g.getMessage("A_userscript_wants_to_access_a_cross_origin_resource_");C=c("div","ask_action_buttons message","help","connect");const S=m("div","help","connect");let J=g.getMessage("A_request_to_a_cross_origin_resource_is_nothing_unusual__You_just_have_to_check_whether_this_script_has_a_good_reason_to_access_this_domain__For_example_there_are_only_a_very_few_reasons_for_a_userscript_to_contact_your_bank__Please_note_that_userscript_authors_can_avoid_this_dialog_by_adding_@connect_tags_to_their_scripts__You_can_change_your_opinion_at_any_time_at_the_scripts_settings_tab_",
a.connect_url,a.settings_url);J=u.safeTagsReplace(J).replace(/\[url=([^\]]+)\](.*)\[\/url\]/g,'<a target="_blank" href="$1">$2 &#x2B00;</a>').replace(/\n/g,"<br>");S.innerHTML=J+"<br><br>";C.appendChild(S);Q.appendChild(I);l.appendChild([r,C,p,G]);n.appendChild(l);const T=c("table","script_desc","connect");[{prop:"name",label:g.getMessage("Name")},{prop:"src_url",label:g.getMessage("Tab_URL")},a.domain?{prop:"hostname",label:g.getMessage("Destination_domain")}:null,{prop:"url",label:g.getMessage("Destination_URL")}].forEach(b=>
{if(b){var f=a[b.prop]||a.script[b.prop]||b.value,d=c("tr","script_desc",b.prop,"connect"),e=c("td","script_desc",b.prop,"connectdt"),h=c("td","script_desc",b.prop,"connectdd");e.textContent=b.label?b.label:"";h.textContent=f||g.getMessage("_not_set_");d.appendChild(e);d.appendChild(h);T.appendChild(d)}});R.appendChild(T);P.appendChild(R);v.appendChild(Q);v.appendChild(P);t.appendChild(v);l=c("div","section","connect_src","connect");l.appendChild(t);l.appendChild(n);b.appendChild(l)},ja=(b,a)=>{document.title=
g.getMessage("Import");b.appendChild(da(a));if(a.global_settings){const a=c("div","viewer_upper","");ia({content:a,checkbox:"import",key:"global_settings"});b.appendChild(a)}a.scripts&&Object.keys(a.scripts).forEach(f=>{const e=a.scripts[f],d=c("div","viewer_upper",f);K({content:d,preparat:e,checkbox:"import",key:f},!0);b.appendChild(d)})},U=(b,a)=>{const c=m("input",b+"_",a,"",!0);c.setAttribute("data-import-id",a);c.checked=!0;c.type="checkbox";c.addEventListener("click",b=>{(b.ctrlKey||b.metaKey)&&
$("input[type=checkbox][data-import-id!="+a+"]").prop("checked",c.checked)});return c},ia=b=>{var a=b.key;const f=b.content,e=c("div","viewer_upper",a);var d=c("div","viewer_info viewer_info_wide","general",a);const h=c("div","viewer_content","general_content",a);var n=m("h3","install","heading",a);b.checkbox&&n.appendChild(U(b.checkbox,b.key));b=m("img","version","heading",a);b.src=A.brand("tampermonkey");n.appendChild(b);b=m("span","name","heading",a);b.textContent=g.getMessage("Global_Settings");
n.appendChild(b);d.appendChild(n);n=c("table","script_desc",a);b=c("tr","settings_desc","action",a);let l=c("td","settings_desc","action",a+"dt"),p=c("td","settings_desc","action",a+"dd");l.textContent=g.getMessage("Action");p.textContent=g.getMessage("Global_settings_import");b.appendChild(l);b.appendChild(p);n.appendChild(b);b=c("tr","settings_desc","warning",a);l=c("td","settings_desc","warning",a+"dt");p=c("td","settings_desc","warning",a+"dd");a='<i class="far fa-'+A.get("critical")+'"></i>&nbsp;';
z.RUNTIME.MOBILE||(l.innerHTML=a,a="");p.innerHTML=a+u.safeTagsReplace(g.getMessage("This_will_overwrite_your_global_settings_"));b.appendChild(l);b.appendChild(p);n.appendChild(b);h.appendChild(n);d.appendChild(h);e.appendChild(d);d=c("div","section","settings_src");d.appendChild(e);f.appendChild(d)},K=(b,a)=>{const f=b.preparat,e=b.content,d=f.script||{},h=d.uuid||d.id||d.name;f.short_info||(f.short_info=[]);const n=c("div","viewer_upper",h);var l=c("div","viewer_info "+(a?"viewer_info_wide":"viewer_info_multiple"),
"general",h);const p=c("div","viewer_content","general_content",h);var k=m("h3","install","heading",h);b.checkbox&&k.appendChild(U(b.checkbox,b.key));if(d.icon||d.icon64){var r=m("img","version","heading",h);r.src=d.icon||d.icon64;k.appendChild(r)}r=m("span","name","heading",h);r.textContent=f.heading||d.name||"";k.appendChild(r);d.version&&(r=c("span","view_version","heading",h),r.textContent="v"==d.version[0]?"":"v",r.textContent+=d.version,k.appendChild(r));l.appendChild(k);a&&f.short_info.unshift({prop:"heading",
value:f.messages.heading,label:g.getMessage("Action")});const q=c("table","script_desc",h);f.short_info.forEach(b=>{const f=d[b.prop]||b.value;if(f||!a){var e=c("tr","script_desc",b.prop,h),l=c("td","script_desc",b.prop,h+"dt"),k=c("td","script_desc",b.prop,h+"dd");l.textContent=b.label?b.label:"";k.textContent=f||g.getMessage("_not_set_");e.appendChild(l);e.appendChild(k);q.appendChild(e)}});p.appendChild(q);k=c("div","viewer_info viewer_info_multiple","info",h);let v;a?v=p:(v=c("div","viewer_content",
"info_content",h),r=m("h4","action","heading",h),document.title=r.textContent=f.messages.heading,v.appendChild(r));let t=0;["errors","warnings","info"].forEach(a=>{const b=m("table",a,h+t);(f.messages[a]||[]).forEach(c=>{t++;const f=m("tr",a,h+t),d=m("td",a,h+"dt"+t),e=m("td",a,h+"dd"+t);if("info"==a)if(c.label&&c.value)d.textContent=c.label,e.textContent=c.value;else{var g='<i class="far fa-'+A.get("info")+'"></i>&nbsp;';z.RUNTIME.MOBILE||(d.innerHTML=g,g="");e.innerHTML=g+u.safeTagsReplace(c).replace(/\n/g,
"<br />")}else"warnings"==a?(g='<i class="far fa-'+A.get("critical")+'"></i>&nbsp;',z.RUNTIME.MOBILE||(d.innerHTML=g,g=""),e.innerHTML=g+u.safeTagsReplace(c).replace(/\n/g,"<br />")):"errors"==a&&(g='<i class="far fa-'+A.get("error")+'"></i>&nbsp;',z.RUNTIME.MOBILE||(d.innerHTML=g,g=""),e.innerHTML=g+u.safeTagsReplace(c).replace(/\n/g,"<br />"));f.appendChild(d);f.appendChild(e);b.appendChild(f)});v.appendChild(b)});r=(a,b,f,e)=>{const l=m("table",a,h);let k=0;const n={};b.forEach(b=>{if(!(k>e||n[b])){n[b]=
!0;var d=c("tr",a+"desc",b,h+k),g=c("td",a+"desc",b,h+k+"dt"),m=c("td",a+"desc",b,h+k+"dd");g.innerHTML=0==k?u.safeTagsReplace(f.label):"&nbsp;";m.innerHTML=k==e?'<span title="'+u.safeTagsReplace(f.warning)+'">...!</span>':u.safeTagsReplace(b);d.appendChild(g);d.appendChild(m);l.appendChild(d);k++}});if(d.options&&(b=d.options.override&&d.options.override["use_"+a])&&b.length){b=c("tr",a+"desc","ovverride",h+k);const d=c("td",a+"desc","ovverride",h+k+"dt"),e=c("td",a+"desc","ovverride",h+k+"dd");
d.innerHTML=0==k?u.safeTagsReplace(f.label):"&nbsp;";e.innerHTML=u.safeTagsReplace(" ("+g.getMessage("overwritten_by_user")+")");b.appendChild(d);b.appendChild(e);l.appendChild(b)}v.appendChild(l)};r("includes",(d.includes||[]).concat(d.matches||[]),{label:g.getMessage("Include_s__"),warning:g.getMessage("Attention_Can_not_display_all_includes_")},5);r("excludes",d.excludes||[],{label:g.getMessage("Exclude_s__"),warning:g.getMessage("Attention_Can_not_display_all_excludes_")},3);l.appendChild(p);
k.appendChild(v);n.appendChild(l);n.appendChild(k);l=c("div","section",h,"install_src");l.appendChild(n);b.install&&l.appendChild(b.install(f));b.editor&&l.appendChild(b.editor(f));e.appendChild(l)},ba=b=>{q(k.aid,"abort");window.setTimeout(()=>{window.location=b+"#bypass=true"},10)};var y=b=>{q(k.aid,"abort");window.setTimeout(()=>{window.close()},3E3)};const V=(b,a)=>{q(k.aid,"unload");F&&(window.clearInterval(F),F=null);window.removeEventListener("unload",V)};window.addEventListener("unload",V);
const W=()=>{window.location.search||window.location.hash?(k=w.getUrlArgs(),k.aid?(q(k.aid,"preparat").done(b=>{b.ext&&b.ext.version&&(O=b.ext.version);if(b.options&&(b.options.statistics_enabled&&X.init("ask",O,!0),b.options.layout_user_css)){const a=document.createElement("style");a.innerHTML=b.options.layout_user_css;(document.head||document.body||document.documentElement||document).appendChild(a)}N=g.getMessage("Install");let a=null;b.preparat&&("install"==b.type?a=()=>{K({content:B(),preparat:b.preparat,
install:ca,editor:Z})}:"install_error"==b.type?a=()=>{K({content:B(),preparat:b.preparat,install:ea},!0)}:"import"==b.type?a=()=>{ja(B(),b.preparat)}:"permission"==b.type?a=()=>{fa(B(),b.preparat)}:"connect"==b.type&&(a=()=>{ha(B(),b.preparat)}),F=window.setInterval(H,3E3),a&&window.setTimeout(()=>{a();var c,e;(c=b.preparat)&&(e=c.hints)&&e.length&&e.forEach(a=>{a.globalhint&&u.createGobalHint(a.options,$("body > div.status")[0])})},1))}).fail(()=>{y()}),E.wait(g.getMessage("Please_wait___"))):y()):
window.onhashchange=()=>{W()}};rea.extension.onMessage.addListener((b,a,c)=>{t=b.options||t;if("confirm"==b.method)w.confirm(b.msg,a=>{c({confirm:a})});else if("showMsg"==b.method)w.alert(b.msg),c({});else return!1;return!0});M.addStyle(W)})});
